// Tap a dino: treat (hearts), pat a hungry carnivore ("Nope!"), take a photo.
import puppeteer from 'puppeteer-core';
const OUT = new URL('.', import.meta.url).pathname;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const [W, H] = (process.argv[2] ?? '844x390').split('x').map(Number);
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.setViewport({ width: W, height: H, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await page.goto('http://localhost:5173/?quickstart', { waitUntil: 'load' });
await sleep(1200);
const ids = await page.evaluate(() => {
  const { sim, game } = window.__dino; const s = sim.state; s.money = 1e6; sim.setSpeed(0);
  s.parcelsOwned = s.parcelsOwned.map(() => true); s.unlockedSpecies.push('allosaurus');
  const { x: ex, y: ey } = s.entrance;
  const A = { x: ex - 5, y: ey - 11 }, C = { x: ex + 5, y: ey - 3 };
  const edges = [];
  for (let x = A.x; x < C.x; x++) edges.push({ dir: 'h', x, y: A.y }, { dir: 'h', x, y: C.y });
  for (let y = A.y; y < C.y; y++) edges.push({ dir: 'v', x: A.x, y }, { dir: 'v', x: C.x, y });
  sim.dispatch({ type: 'buildFences', edges, fence: 4 });
  sim.dispatch({ type: 'buyDino', species: 'triceratops', x: A.x + 3, y: A.y + 5 });
  sim.dispatch({ type: 'buyDino', species: 'dilophosaurus', x: A.x + 7, y: A.y + 5 });
  const [trike, dilo] = s.dinos; dilo.hunger = 80;
  const cam = game.scene.getScene('park').cameras.main; cam.setZoom(3); cam.centerOn((A.x + 5) * 16, (A.y + 4) * 16);
  return { trike: trike.id, dilo: dilo.id };
});
await sleep(600);
const tapDino = async (id) => {
  const p = await page.evaluate((id) => { const sc = window.__dino.game.scene.getScene('park'); const d = window.__dino.sim.state.dinos.find((x) => x.id === id); const q = sc.entities.dinoPosition(d); const c = sc.cameras.main; const cx = c.width / 2, cy = c.height / 2; return { x: (q.x - c.scrollX - cx) * c.zoom + cx, y: (q.y - 10 - c.scrollY - cy) * c.zoom + cy }; }, id);
  await page.touchscreen.tap(p.x, p.y); await sleep(350);
};
const buttons = () => page.$$eval('#info-actions button:not([hidden]):not(.hidden)', (b) => b.map((x) => `${x.textContent}${x.disabled ? '(off)' : ''}`));
await tapDino(ids.trike);
console.log('trike buttons:', await buttons());
const smalls = await page.$$('#info-actions .action-btn.small');
await smalls[0].tap(); await sleep(250);
await page.screenshot({ path: `${OUT}care-1-treat-${W}.png` });
console.log('after treat:', await buttons(), '| toast:', await page.$$eval('.toast', (t) => t.at(-1)?.textContent));
await tapDino(ids.dilo);
await (await page.$$('#info-actions .action-btn.small'))[1].tap(); await sleep(250);
await page.screenshot({ path: `${OUT}care-2-nope-${W}.png` });
console.log('pat hungry dilo toast:', await page.$$eval('.toast', (t) => t.at(-1)?.textContent));
await tapDino(ids.trike);
await (await page.$$('#info-actions .action-btn.small'))[2].tap(); await sleep(1200);
const photo = await page.evaluate(() => { const m = document.getElementById('photo'); const img = m.querySelector('.photo-img'); return { open: !m.classList.contains('hidden'), w: img.naturalWidth, h: img.naturalHeight, photos: window.__dino.sim.state.stats.photos }; });
console.log('photo:', photo);
await page.screenshot({ path: `${OUT}care-3-photo-${W}.png` });
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
