import puppeteer from 'puppeteer-core';
const OUT = new URL('.', import.meta.url).pathname;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.setViewport({ width: 844, height: 390, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await page.goto('http://localhost:5173/?quickstart', { waitUntil: 'networkidle0' });
await sleep(500);
await page.evaluate(() => { const { sim } = window.__dino; sim.state.speed = 4; });
await page.evaluate(() => { const { sim } = window.__dino; for (let i = 0; i < 24 * 3 * 4; i++) sim.step(); });
await sleep(300);
const badge = await page.$eval('#log-badge', (b) => ({ text: b.textContent, hidden: b.classList.contains('hidden') }));
console.log('badge:', badge, 'log size', await page.evaluate(() => window.__dino.sim.state.log.length));
await (await page.$('#btn-log')).tap(); await sleep(300);
const r = await page.evaluate(() => ({ rows: document.querySelectorAll('#log .log-entry').length, first: document.querySelector('#log .log-entry')?.textContent.trim().replace(/\s+/g, ' '), card: document.querySelector('#log .modal-card').getBoundingClientRect().bottom, vh: innerHeight, badgeHidden: document.getElementById('log-badge').classList.contains('hidden') }));
console.log('open:', r);
await page.screenshot({ path: `${OUT}log-all.png` });
await (await page.$('[data-filter="reports"]')).tap(); await sleep(200);
console.log('reports:', await page.$$eval('#log .log-entry', (e) => e.length));
await page.screenshot({ path: `${OUT}log-reports.png` });
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
