import puppeteer from 'puppeteer-core';
import { HERE, finish } from './lib.mjs';
const OUT = HERE;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.setViewport({ width: 667, height: 375, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle0' });
await page.evaluate(async () => { localStorage.clear(); await new Promise((r) => { const q = indexedDB.deleteDatabase('dino-tycoon'); q.onsuccess = q.onerror = q.onblocked = r; }); });
await page.reload({ waitUntil: 'networkidle0' });
await sleep(400);
await (await page.$('[data-go="new"]')).tap(); await sleep(300);
await page.screenshot({ path: `${OUT}ms-0-cards.png` });
await (await page.$('[data-scenario="first-steps"]')).tap(); await sleep(900);
await (await page.$('.tutorial-skip-all'))?.tap(); await sleep(300);
await page.evaluate(() => {
  const { sim } = window.__dino; const s = sim.state;
  s.stats.bestDayVisitors = 50; s.reputation = 60;
  const { x, y } = s.entrance;
  for (let i = 0; i < 4; i++) s.dinos.push({ id: 900 + i, species: 'protoceratops', name: 'T' + i, x, y, px: x, py: y, path: [], hunger: 0, health: 100, happiness: 100, bornHour: 0, sick: false, escaped: false, homeX: x, homeY: y });
  for (let i = 0; i < 16; i++) sim.step();
});
await sleep(500);
const pop = await page.evaluate(() => ({ visible: !document.getElementById('outcome').classList.contains('hidden'), text: document.querySelector('#outcome .outcome-body').innerText.replace(/\n+/g, ' | ') }));
console.log('popup:', pop);
await page.screenshot({ path: `${OUT}ms-1-popup.png` });
await (await page.$('[data-outcome="keep"]')).tap(); await sleep(300);
await (await page.$('#btn-park')).tap(); await sleep(400);
await page.screenshot({ path: `${OUT}ms-2-goals.png` });
console.log('unlocked:', await page.evaluate(() => window.__dino.sim.state.unlockedSpecies.join(',')));
finish(errors);
await browser.close();
