import puppeteer from 'puppeteer-core';
const OUT = new URL('.', import.meta.url).pathname;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
const [W, H] = (process.argv[2] ?? '844x390').split('x').map(Number);
await page.setViewport({ width: W, height: H, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await page.goto('http://localhost:5173/?quickstart', { waitUntil: 'networkidle0' });
await sleep(500);
const r = await page.evaluate(() => {
  const { sim, game } = window.__dino; const s = sim.state; s.money = 1e7;
  const { x: ex, y: ey } = s.entrance; const w = s.map.width;
  const A = { x: ex - 6, y: ey - 10 }, C = { x: ex + 6, y: ey - 4 };
  const edges = [];
  for (let x = A.x; x < C.x; x++) edges.push({ dir: 'h', x, y: A.y }, { dir: 'h', x, y: C.y });
  for (let y = A.y; y < C.y; y++) edges.push({ dir: 'v', x: A.x, y }, { dir: 'v', x: C.x, y });
  sim.dispatch({ type: 'buildFences', edges, fence: 1 });
  sim.dispatch({ type: 'placeFeeder', kind: 'plants', x: A.x + 1, y: A.y + 1 });
  for (const [sp, dx] of [['triceratops', 3], ['parasaurolophus', 6], ['stegosaurus', 9], ['velociraptor', 5]]) sim.dispatch({ type: 'buyDino', species: sp, x: A.x + dx, y: A.y + 3 });
  const tiles = []; for (let x = ex - 7; x <= ex + 7; x++) tiles.push((ey - 3) * w + x); tiles.push((ey - 2) * w + ex, (ey - 1) * w + ex);
  sim.dispatch({ type: 'buildPaths', tiles });
  for (const [kind, dx] of [['snackstall', -5], ['snackstall', 4], ['giftshop', -2]]) sim.dispatch({ type: 'placeBuilding', kind, x: ex + dx, y: ey - 2 });
  sim.dispatch({ type: 'placeBuilding', kind: 'trashcan', x: ex + 6, y: ey - 2 });
  for (const role of ['mascot', 'janitor', 'worker', 'vet']) sim.dispatch({ type: 'hireStaff', role });
  s.ticketPrice = 28; s.reputation = 90;
  for (let i = 0; i < 16 * 7; i++) sim.step();
  s.stormHours = 3;
  for (let i = 0; i < 16 * 1; i++) sim.step();
  const cam = game.scene.getScene('park').cameras.main; cam.setZoom(4); cam.centerOn((ex - 1) * 16, (ey - 4) * 16);
  const held = { snack: s.visitors.filter((v) => v.snack).length, soda: s.visitors.filter((v) => v.sodaUntil > 0).length, umbrella: s.visitors.filter((v) => v.items.includes('umbrella')).length };
  return { visitors: s.visitors.length, reviews: s.reviews.length, messes: s.messes.map((m) => m.kind).join(''), held, log: s.log.slice(-4).map((l) => l.text) };
});
console.log(JSON.stringify(r, null, 1));
await sleep(700);
await page.screenshot({ path: `${OUT}people-0-park-${W}.png` });
await (await page.$('#btn-people')).tap(); await sleep(300);
await page.screenshot({ path: `${OUT}people-1-visitors-${W}.png` });
await page.evaluate(() => { document.querySelector('.people-body').scrollTop = 120; }); await sleep(100);
await page.screenshot({ path: `${OUT}people-1b-cards-${W}.png` });
const fit = await page.evaluate(() => { const c = document.querySelector('#people .modal-card').getBoundingClientRect(); const b = document.querySelector('.people-body'); return { top: c.top, bottom: c.bottom, vh: innerHeight, scrolls: b.scrollHeight > b.clientHeight, docW: document.documentElement.scrollWidth, vw: innerWidth }; });
console.log('fit', fit);
await (await page.$('[data-filter="gross"]'))?.tap(); await sleep(200);
console.log('gross chip:', await page.$$eval('#people .person-card', (c) => c.length));
await (await page.$('[data-filter="all"]')).tap(); await sleep(200);
// Rename the first visitor.
const renameBtn = await page.$('[data-rename^="visitor:"]');
if (renameBtn) {
  await renameBtn.tap(); await sleep(200);
  await page.keyboard.down('Meta'); await page.keyboard.press('a'); await page.keyboard.up('Meta');
  await page.keyboard.type('Rosa Q.');
  await page.keyboard.press('Enter'); await sleep(200);
  console.log('renamed:', await page.evaluate(() => window.__dino.sim.state.visitors.filter((v) => v.name === 'Rosa Q.').length));
} else console.log('renamed: skipped (no visitors on this island yet)');
for (const t of ['reviews', 'dinos', 'staff']) {
  await (await page.$(`[data-tab="${t}"]`)).tap(); await sleep(300);
  await page.screenshot({ path: `${OUT}people-2-${t}-${W}.png` });
}
await (await page.$('[data-tab="dinos"]')).tap(); await sleep(200);
await (await page.$('[data-locate^="dino:"]')).tap(); await sleep(700);
console.log('after locate:', await page.evaluate(() => ({ hidden: document.getElementById('people').classList.contains('hidden'), info: document.getElementById('info-text').textContent })));
await page.screenshot({ path: `${OUT}people-3-locate-${W}.png` });
console.log('errors:', errors.length ? errors : 'none');
await browser.close();
